name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Create/update tag for manual release
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        TAG="${{ github.event.inputs.tag }}"
        
        # Delete existing tag and release if they exist
        git tag -d $TAG 2>/dev/null || true
        git push origin :refs/tags/$TAG 2>/dev/null || true
        
        # Create new tag from current main
        git tag $TAG
        git push origin $TAG
        echo "Created/updated tag: $TAG"

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}